# this is the build file for project 
# it is autogenerated by the xmake build system.
# do not edit by hand.

MM=/usr/bin/gcc
CC=/usr/bin/gcc
MXX=/usr/bin/gcc
AS=/usr/bin/gcc
CXX=/usr/bin/gcc

LD=/usr/bin/g++
SH=/usr/bin/g++
AR=/usr/bin/ar

particles_CXXFLAGS=-m64 -Iinclude
particles_CXXFLAGS=-m64 -Iinclude
particles_LDFLAGS=-m64 -Llib -Lbuild/linux/x86_64/release -lxd -lglad -lglfw3 -lrt -lm -ldl -lX11 -lpthread -llibrary
library_CXXFLAGS=-m64 -Iinclude
library_CXXFLAGS=-m64 -Iinclude
library_ARFLAGS=-cr
brownian_motion_CXXFLAGS=-m64 -Iinclude
brownian_motion_CXXFLAGS=-m64 -Iinclude
brownian_motion_LDFLAGS=-m64 -Llib -Lbuild/linux/x86_64/release -lxd -lglad -lglfw3 -lrt -lm -ldl -lX11 -lpthread -llibrary
newtons_cannon_CXXFLAGS=-m64 -Iinclude
newtons_cannon_CXXFLAGS=-m64 -Iinclude
newtons_cannon_LDFLAGS=-m64 -Llib -Lbuild/linux/x86_64/release -lxd -lglad -lglfw3 -lrt -lm -ldl -lX11 -lpthread -llibrary

default:  particles library brownian_motion newtons_cannon

all:  particles library brownian_motion newtons_cannon

.PHONY: default all  particles library brownian_motion newtons_cannon

particles: build/linux/x86_64/release/particles
build/linux/x86_64/release/particles: build/linux/x86_64/release/liblibrary.a build/.objs/particles/linux/x86_64/release/src/particles.cpp.o
	@echo linking.release particles
	@mkdir -p build/linux/x86_64/release
	@$(LD) -o build/linux/x86_64/release/particles build/.objs/particles/linux/x86_64/release/src/particles.cpp.o $(particles_LDFLAGS) > build/.build.log 2>&1

build/.objs/particles/linux/x86_64/release/src/particles.cpp.o: src/particles.cpp
	@echo compiling.release src/particles.cpp
	@mkdir -p build/.objs/particles/linux/x86_64/release/src
	@$(CXX) -c $(particles_CXXFLAGS) -o build/.objs/particles/linux/x86_64/release/src/particles.cpp.o src/particles.cpp > build/.build.log 2>&1

library: build/linux/x86_64/release/liblibrary.a
build/linux/x86_64/release/liblibrary.a: build/.objs/library/linux/x86_64/release/lib/object.cpp.o build/.objs/library/linux/x86_64/release/lib/particle.cpp.o build/.objs/library/linux/x86_64/release/lib/vector3d.cpp.o
	@echo linking.release liblibrary.a
	@mkdir -p build/linux/x86_64/release
	@$(AR) $(library_ARFLAGS) build/linux/x86_64/release/liblibrary.a build/.objs/library/linux/x86_64/release/lib/object.cpp.o build/.objs/library/linux/x86_64/release/lib/particle.cpp.o build/.objs/library/linux/x86_64/release/lib/vector3d.cpp.o > build/.build.log 2>&1

build/.objs/library/linux/x86_64/release/lib/object.cpp.o: lib/object.cpp
	@echo compiling.release lib/object.cpp
	@mkdir -p build/.objs/library/linux/x86_64/release/lib
	@$(CXX) -c $(library_CXXFLAGS) -o build/.objs/library/linux/x86_64/release/lib/object.cpp.o lib/object.cpp > build/.build.log 2>&1

build/.objs/library/linux/x86_64/release/lib/particle.cpp.o: lib/particle.cpp
	@echo compiling.release lib/particle.cpp
	@mkdir -p build/.objs/library/linux/x86_64/release/lib
	@$(CXX) -c $(library_CXXFLAGS) -o build/.objs/library/linux/x86_64/release/lib/particle.cpp.o lib/particle.cpp > build/.build.log 2>&1

build/.objs/library/linux/x86_64/release/lib/vector3d.cpp.o: lib/vector3d.cpp
	@echo compiling.release lib/vector3d.cpp
	@mkdir -p build/.objs/library/linux/x86_64/release/lib
	@$(CXX) -c $(library_CXXFLAGS) -o build/.objs/library/linux/x86_64/release/lib/vector3d.cpp.o lib/vector3d.cpp > build/.build.log 2>&1

brownian_motion: build/linux/x86_64/release/brownian_motion
build/linux/x86_64/release/brownian_motion: build/linux/x86_64/release/liblibrary.a build/.objs/brownian_motion/linux/x86_64/release/src/brownian_motion.cpp.o
	@echo linking.release brownian_motion
	@mkdir -p build/linux/x86_64/release
	@$(LD) -o build/linux/x86_64/release/brownian_motion build/.objs/brownian_motion/linux/x86_64/release/src/brownian_motion.cpp.o $(brownian_motion_LDFLAGS) > build/.build.log 2>&1

build/.objs/brownian_motion/linux/x86_64/release/src/brownian_motion.cpp.o: src/brownian_motion.cpp
	@echo compiling.release src/brownian_motion.cpp
	@mkdir -p build/.objs/brownian_motion/linux/x86_64/release/src
	@$(CXX) -c $(brownian_motion_CXXFLAGS) -o build/.objs/brownian_motion/linux/x86_64/release/src/brownian_motion.cpp.o src/brownian_motion.cpp > build/.build.log 2>&1

newtons_cannon: build/linux/x86_64/release/newtons_cannon
build/linux/x86_64/release/newtons_cannon: build/linux/x86_64/release/liblibrary.a build/.objs/newtons_cannon/linux/x86_64/release/src/newtons_cannon.cpp.o
	@echo linking.release newtons_cannon
	@mkdir -p build/linux/x86_64/release
	@$(LD) -o build/linux/x86_64/release/newtons_cannon build/.objs/newtons_cannon/linux/x86_64/release/src/newtons_cannon.cpp.o $(newtons_cannon_LDFLAGS) > build/.build.log 2>&1

build/.objs/newtons_cannon/linux/x86_64/release/src/newtons_cannon.cpp.o: src/newtons_cannon.cpp
	@echo compiling.release src/newtons_cannon.cpp
	@mkdir -p build/.objs/newtons_cannon/linux/x86_64/release/src
	@$(CXX) -c $(newtons_cannon_CXXFLAGS) -o build/.objs/newtons_cannon/linux/x86_64/release/src/newtons_cannon.cpp.o src/newtons_cannon.cpp > build/.build.log 2>&1

clean:  clean_particles clean_library clean_brownian_motion clean_newtons_cannon

clean_particles:  clean_library
	@rm -rf build/linux/x86_64/release/particles
	@rm -rf build/linux/x86_64/release/particles.sym
	@rm -rf build/.objs/particles/linux/x86_64/release/src/particles.cpp.o

clean_library: 
	@rm -rf build/linux/x86_64/release/liblibrary.a
	@rm -rf build/linux/x86_64/release/library.sym
	@rm -rf build/.objs/library/linux/x86_64/release/lib/object.cpp.o
	@rm -rf build/.objs/library/linux/x86_64/release/lib/particle.cpp.o
	@rm -rf build/.objs/library/linux/x86_64/release/lib/vector3d.cpp.o

clean_brownian_motion:  clean_library
	@rm -rf build/linux/x86_64/release/brownian_motion
	@rm -rf build/linux/x86_64/release/brownian_motion.sym
	@rm -rf build/.objs/brownian_motion/linux/x86_64/release/src/brownian_motion.cpp.o

clean_newtons_cannon:  clean_library
	@rm -rf build/linux/x86_64/release/newtons_cannon
	@rm -rf build/linux/x86_64/release/newtons_cannon.sym
	@rm -rf build/.objs/newtons_cannon/linux/x86_64/release/src/newtons_cannon.cpp.o

