target("library")
    set_kind("static")
    add_includedirs("include")
    add_files("lib/*.cpp")

target("particles")
    set_kind("binary")
    add_linkdirs("lib")
    add_links("xd", "glad", "glfw3", "rt", "m", "dl", "X11", "pthread")
    add_includedirs("include")
    add_files("src/particles.cpp")
    add_deps("library")

target("brownian_motion")
    set_kind("binary")
    add_linkdirs("lib")
    add_links("xd", "glad", "glfw3", "rt", "m", "dl", "X11", "pthread")
    add_includedirs("include")
    add_files("src/brownian_motion.cpp")
    add_deps("library")

target("newtons_cannon")
    set_kind("binary")
    add_linkdirs("lib")
    add_links("xd", "glad", "glfw3", "rt", "m", "dl", "X11", "pthread")
    add_includedirs("include")
    add_files("src/newtons_cannon.cpp")
    add_deps("library")